---
name: Java CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        java: [8, 11, 17]
      fail-fast: false
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v2
        env:
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}
      - name: Test with Maven
        run: mvn test -B
      - name: Generate code coverage
      # https://github.com/marketplace/actions/codecov
      - uses: codecov/codecov-action@v2
        with:
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
